version: "3.2"
services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 8081:8000
    environment:
      DATABASE_HOST: database
      DATABASE_USER: api_user
      DATABASE_PASSWORD: api_password
      DATABASE_NAME: api_database
      DATABASE_PORT: 5432
      APP_DEBUG: 1
      APP_SECRET_KEY: a
    links: 
      - database
  
  database:
    image: postgres:12
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: api_password
      POSTGRES_USER: api_user
      POSTGRES_DB: api_database
  
  adminer:
    image: adminer
    ports:
      - 8082:8080
    links:
      - database