# Generated by Django 2.2.9 on 2020-01-19 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='situation_threads', to='api.Situation', verbose_name='situation')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='situation_threads', to='api.Strategy', verbose_name='strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_threads', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'situation_thread',
                'verbose_name_plural': 'situation_threads',
            },
        ),
        migrations.CreateModel(
            name='SituationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('description', models.TextField(verbose_name='description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='situation_comments', to='api.SituationComment', verbose_name='parent')),
                ('situation_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_comments', to='api.SituationThread', verbose_name='situation_thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'situation_comment',
                'verbose_name_plural': 'situation_comments',
            },
        ),
        migrations.CreateModel(
            name='SituationCategoryThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('situation_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='situation_category_threads', to='api.SituationCategory', verbose_name='situation_category')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='situation_category_threads', to='api.Strategy', verbose_name='strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_category_threads', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'situation_category_thread',
                'verbose_name_plural': 'situation_category_threads',
            },
        ),
        migrations.CreateModel(
            name='SituationCategoryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('description', models.TextField(verbose_name='description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='situation_category_comments', to='api.SituationCategoryComment', verbose_name='parent')),
                ('situation_category_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_category_comments', to='api.SituationCategoryThread', verbose_name='situation_category_thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_category_comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'situation_category_comment',
                'verbose_name_plural': 'situation_category_comments',
            },
        ),
        migrations.CreateModel(
            name='BuildingBlockThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('building_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='building_block_threads', to='api.BuildingBlock', verbose_name='building_block')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='building_block_threads', to='api.Strategy', verbose_name='strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_block_threads', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'building_block_thread',
                'verbose_name_plural': 'building_block_threads',
            },
        ),
        migrations.CreateModel(
            name='BuildingBlockComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('description', models.TextField(verbose_name='description')),
                ('building_block_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_block_comments', to='api.BuildingBlockThread', verbose_name='building_block_thread')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_block_comments', to='api.BuildingBlockComment', verbose_name='parent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_block_comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'building_block_comment',
                'verbose_name_plural': 'building_block_comments',
            },
        ),
    ]
