# Generated by Django 2.2.9 on 2020-01-25 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_buildingblockcomment_buildingblockthread_situationcategorycomment_situationcategorythread_situationc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='country',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_representative',
        ),
        migrations.AddField(
            model_name='buildingblockthread',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is_closed'),
        ),
        migrations.AddField(
            model_name='situationcategorythread',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is_closed'),
        ),
        migrations.AddField(
            model_name='situationthread',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is_closed'),
        ),
        migrations.AddField(
            model_name='strategymeasurethread',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is_closed'),
        ),
        migrations.CreateModel(
            name='StrategyThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('is_closed', models.BooleanField(default=False, verbose_name='is_closed')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_threads', to='api.Strategy', verbose_name='strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_threads', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'strategy_thread',
                'verbose_name_plural': 'strategy_threads',
            },
        ),
        migrations.CreateModel(
            name='StrategyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('description', models.TextField(verbose_name='description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_comments', to='api.StrategyComment', verbose_name='parent')),
                ('strategy_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_comments', to='api.StrategyThread', verbose_name='strategy_thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'strategy_comment',
                'verbose_name_plural': 'strategy_comments',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.Country', verbose_name='country')),
                ('users', models.ManyToManyField(blank=True, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'board',
                'verbose_name_plural': 'boards',
            },
        ),
        migrations.AddField(
            model_name='strategy',
            name='board',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Board', verbose_name='board'),
        ),
    ]
