# Generated by Django 2.2.9 on 2020-01-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200115_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
    ]
