# Generated by Django 2.2.9 on 2020-01-22 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def gen_board(apps, schema_editor):
    Board = apps.get_model('api', 'Board')
    Country = apps.get_model('api', 'Country')
    Board.objects.create(
        country=Country.objects.all().first(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_buildingblockcomment_buildingblockthread_situationcategorycomment_situationcategorythread_situationc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='country',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_representative',
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.Country', verbose_name='country')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'board',
                'verbose_name_plural': 'boards',
            },
        ),
        migrations.RunPython(gen_board, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='strategy',
            name='board',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Board', verbose_name='board'),
            preserve_default=False,
        ),
    ]
