# Generated by Django 2.2.9 on 2020-01-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200125_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.Board', verbose_name='board'),
        ),
    ]
