# Generated by Django 2.2.9 on 2020-01-23 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_strategycomment_strategythread'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingblockthread',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is_closed'),
        ),
        migrations.AddField(
            model_name='situationcategorythread',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is_closed'),
        ),
        migrations.AddField(
            model_name='situationthread',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is_closed'),
        ),
        migrations.AddField(
            model_name='strategymeasurethread',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is_closed'),
        ),
        migrations.AddField(
            model_name='strategythread',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is_closed'),
        ),
        migrations.AlterField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
