# Generated by Django 2.2.9 on 2020-02-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategymeasurethread',
            name='strategy_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_measure_threads', to='api.StrategyMeasure', verbose_name='strategy_measure'),
        ),
    ]
