# Generated by Django 2.2.9 on 2020-02-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200201_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='board',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='buildingblockthread',
            name='building_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_block_threads', to='api.BuildingBlock', verbose_name='building_block'),
        ),
        migrations.AlterField(
            model_name='buildingblockthread',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_block_threads', to='api.Strategy', verbose_name='strategy'),
        ),
        migrations.AlterField(
            model_name='situationcategorythread',
            name='situation_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_category_threads', to='api.SituationCategory', verbose_name='situation_category'),
        ),
        migrations.AlterField(
            model_name='situationcategorythread',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_category_threads', to='api.Strategy', verbose_name='strategy'),
        ),
        migrations.AlterField(
            model_name='situationthread',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_threads', to='api.Situation', verbose_name='situation'),
        ),
        migrations.AlterField(
            model_name='situationthread',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_threads', to='api.Strategy', verbose_name='strategy'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Board', verbose_name='board'),
        ),
        migrations.AlterField(
            model_name='strategymeasure',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_measures', to='api.Measure'),
        ),
        migrations.AlterField(
            model_name='strategymeasure',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_measures', to='api.Strategy'),
        ),
        migrations.AlterField(
            model_name='strategythread',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_threads', to='api.Strategy', verbose_name='strategy'),
        ),
    ]
