from api.resources.auth import AuthViewSet
from api.resources.building_block import BuildingBlockViewSet
from api.resources.comment import CommentViewSet
from api.resources.discussion import DiscussionViewSet
from api.resources.country import CountryViewSet
from api.resources.goal import GoalViewSet
from api.resources.measure import MeasureViewSet
from api.resources.situation import SituationViewSet
from api.resources.strategy import StrategyViewSet
from api.resources.thread import ThreadViewSet
from api.resources.user import UserViewSet
