# AuthViewSet
APP_ERROR_REGISTER_EMAIL_EXISTS = 'APP_ERROR_REGISTER_EMAIL_EXISTS'
APP_ERROR_LOGIN_DOES_NOT_EXIST = 'APP_ERROR_LOGIN_DOES_NOT_EXIST'
APP_ERROR_LOGIN_WRONG_PASSWORD = 'APP_ERROR_LOGIN_WRONG_PASSWORD'

# StrategyViewSet
APP_ERROR_COUNTRY_HAS_STRATEGY = 'APP_ERROR_COUNTRY_HAS_STRATEGY'
